feat: создать сущности: пользователи и вещи и операции с ними
SwShow/java-shareit pull request #1
Opened 2022-11-25 18:23 UTC by SwShow

2022-11-25 20:13 UTC, andrew-larkin requested changes
Привет! Отличная работа, остается внести пару штрихов в архитектуре и мы будем готовы двигаться дальше.

2022-11-25 20:13 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
предлагаю посмотреть на маленькую библиотеку mapStruct - она позволяет создавать мапперы в одну строку, очень удобно

2022-11-25 20:13 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long idUser;
лучше userId

2022-11-25 20:13 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (idUser.isPresent() && idUser.get() > 0) {
от дополнительной логики в контроллерах лучше избавиться - перенести ее в сервис. Почему - контроллеры выступают в роли маршрутизаторов запросов, поступаемых от клиента, передают информацию внутрь приложения и возвращают клиенту ответ. Здесь должен сохраняться один из принципов SOLID, единственная ответственность: каждый класс выполняет единственную задачу, ради которой он создается. Все доп.манипуляции с данными имеют отношение к бизнес-логике, а она помещается, как правило, в сервисы.

2022-11-25 20:13 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto updateItem(@RequestHeader("X-Sharer-User-Id") Optional<Long> idUser, @PathVariable Long itemId,
в реальных проектах ответы контроллера, как правило, оборачиваются в класс ResponseEntity - он позволяет возвращать не только json, но также информацию в хэдере и http-статус, что очень удобно. Очень рекомендую попробовать

2022-11-26 17:00 UTC, SwShow commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
Потратила день, не получилось, эта библиотека плохо совместилась с Lombok, убрала ее

2022-11-26 17:11 UTC, SwShow commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long idUser;
Ok

2022-11-26 18:30 UTC, SwShow commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto updateItem(@RequestHeader("X-Sharer-User-Id") Optional<Long> idUser, @PathVariable Long itemId,
Сделано!

2022-11-26 19:07 UTC, SwShow commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (idUser.isPresent() && idUser.get() > 0) {
Из контроллеров item перенесла, в user остались проверки аннотациями, их тоже убрать?

2022-12-11 16:29 UTC, closed without merging