fix: codeStyle
SwShow/java-shareit pull request #5
Opened 2022-12-11 17:54 UTC by SwShow

2022-12-12 20:55 UTC, andrew-larkin requested changes
Привет! Отлично, очень качественно сделано. Остается пара корректировок и мы будем готовы к встрече с пагинацией)

2022-12-12 20:55 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public static BookingDto toBookingDto(Booking booking) {
если остается время, предлагаю познакомиться с маленькой библиотекой mapStruct, которая позволяет генерировать мапперы в одну строку

2022-12-12 20:55 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @OneToOne
в целом, оно должно работать, но лучше сделать @ManyToOne

2022-12-12 20:55 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @OneToOne
и тут тоже

2022-12-12 20:55 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("select b from Booking b " +
супер!

2022-12-12 20:55 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        userRepository.findById(userId)
вызовы методов поиска юзера повторяются, можно выделить в отдельный приватный метод - это сократит код и дублирование

2022-12-13 14:32 UTC, SwShow commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @OneToOne
Точно!

2022-12-13 14:33 UTC, SwShow commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("select b from Booking b " +
Спасибо

2022-12-14 19:17 UTC, SwShow commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public static BookingDto toBookingDto(Booking booking) {
Библиотекой воспользовалась, но считаю ее лишней, потому что кода становится не меньше, а больше, плюс сама библиотека, наигралась, короче)

2022-12-15 19:07 UTC, merged